<template>
  <div id="coil">
    <h1>Shape your coil</h1>
    <p>Enter the coil parameters and view the results.</p>
    <coil-editor @coilUpdate="coilParamsUpdate($event)" />
    <h1>Coil 3d view</h1>
    <p>Live view of the resulting projectile</p>
    <coil-viewer v-bind:params="coilParams" />
    <h1>Coil Magnetic Field</h1>
    <p>View the magnetic field generated by the coil.</p>
    <p>The current flowing through the coil is set to 1A.</p>
    <graph-viewer v-bind:graph-points="graphData" />
  </div>
</template>

<script>
// @ is an alias to /src
import CoilEditor from "@/components/CoilEditor.vue";
import CoilViewer from "@/components/CoilViewer.vue";
import GraphViewer from "@/components/GraphViewer.vue";

import Vector from "@/vector/vector.js";
import 

export default {
  name: "Coil",
  components: {
    //HelloWorld,
    CoilEditor,
    CoilViewer,
    GraphViewer,
  },
  data: function () {
    return {
      coilParams: { layerCount: 3, layerTurns: 10, wireDia: 1 },
      graphData: {
        points: [
          [0, 0, 0, 0, 0, 0, 0, 0],
          [0, 1, 0, 0, 0, 0, 4, 0],
          [0, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 0, 0, 1, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 2, 0],
          [0, 0, 0, 0, 0, 1, 3, 0],
          [0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0],
        ],
        xDomain: [0, 100],
        yDomain: [0, 100],
        title: "Smooth Contour Lines",
      },
    };
  },
  methods: {
    magneticField() {},
    coilParamsUpdate(event) {
      //Although arrays are passed by reference, since the original array is often spliced, we need to update the references.
      this.coilParams = event;
    },
  },
  mounted() {},
};
</script>
