<template>
  <div id="coil">
    <h1>Shape your coil</h1>
    <p>Enter the coil parameters and view the results.</p>
    <coil-editor @coilUpdate="coilParamsUpdate($event)" />
    <h1>Coil 3d view</h1>
    <p>Live view of the resulting projectile</p>
    <coil-viewer v-bind:params="coilParams" />
    <h1>Coil Magnetic Field</h1>
    <p>View the magnetic field generated by the coil.</p>
    <p>The current flowing through the coil is set to 1A.</p>
    <graph-viewer v-bind:graph-points="graphData" />
  </div>
</template>

<script>
// @ is an alias to /src
import CoilEditor from "@/components/CoilEditor.vue";
import CoilViewer from "@/components/CoilViewer.vue";
import GraphViewer from "@/components/GraphViewer.vue";

import Vector from "@/maxwell/vector.js";
import BiotSavart from "@/maxwell/maxwell.js";

export default {
  name: "Coil",
  components: {
    //HelloWorld,
    CoilEditor,
    CoilViewer,
    GraphViewer,
  },
  data: function () {
    return {
      polygonApprox: 24,
      coilParams: { layerCount: 3, layerTurns: 10, innerRadius: 5, wireDia: 1 },
      coilPoints: [],
      range: { x: [-100, 100], y: [-100, 100], z: [-100, 100] },
      graphData: {
        points: [
          [0, 0, 0, 0, 0, 0, 0, 0],
          [0, 1, 0, 0, 0, 0, 4, 0],
          [0, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 0, 0, 1, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 2, 0],
          [0, 0, 0, 0, 0, 1, 3, 0],
          [0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0],
        ],
        xDomain: [0, 100],
        yDomain: [0, 100],
        title: "Smooth Contour Lines",
      },
    };
  },
  methods: {
    buildGeometry() {
      for (let layer = 0; layer < this.coilParams.layerCount; layer++) {
        for (let turn = 0; turn < this.coilParams.layerTurns; turn++) {
          for (let i = 0; i < this.polygonApprox; i++) {
            
          }
        }
      }
    },
    magneticField() {},
    coilParamsUpdate(event) {
      //Although arrays are passed by reference, since the original array is often spliced, we need to update the references.
      this.coilParams = event;
    },
  },
  mounted() {},
};
</script>
